# Generated by Django 6.0.7 on 2026-07-26 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=200)),
                ('blog_slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('blog_content', models.TextField()),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('blog_category', models.CharField(choices=[('Fertility', 'Fertility'), ('Pregnancy', 'Pregnancy'), ('Donation', 'Donation')], default='Fertility', max_length=20)),
                ('blog_author', models.CharField(default='Dr. Cee Fertility', max_length=100)),
                ('blog_read_time', models.PositiveSmallIntegerField(default=5, help_text='Minutes to read')),
                ('blog_date', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-blog_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Anonymous', max_length=80)),
                ('body', models.TextField(max_length=1200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Home.blog')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-created'],
            },
        ),
    ]
